### PR TITLE
Add AdaBraceMatcher 

### PR DESCRIPTION
**Pull request by benconvey**
This PR adds an AdaBraceMatcher class that highlights the corresponding opening or closing brace to the one at the cursor

### CODE REVIEW

**Comment by benconvey** [comment]
Video of it working [https://youtu.be/xuM7ilt58_I](https://youtu.be/xuM7ilt58_I)

**Comment by setton** [comment]
Hello @benconvey - thank you for this contribution - and for capturing a video as well :)

Are you able to sign the CLA? We're not able to look at the code before this is signed...

**Comment by benconvey** [comment]
Hi @setton 
Sorry about that, it's now signed :)

**Comment by setton** [comment]
Pushing! Thanks again @benconvey for the contribution.

**Pull request merged**
